# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
strategy:
  matrix:
    windows:
      imageName: 'windows-latest'
    #linux:
    #  imageName: 'ubuntu-latest'
    #macos:
    #  imageName: 'macos-latest'
      
pool:
  vmImage: $(imageName)

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
